name: SakuraGuilds
version: ${version}
main: me.xneox.guilds.SakuraGuildsPlugin
author: xNeox
description: Plugin na gildie, dla serwera dronizja.pl
api-version: 1.17

depend:
  - Vault
  - HolographicDisplays
  - PlaceholderAPI
  - EpicGuard
  - AureliumSkills
  - CombatLogX

commands:
  guild:
    aliases: [ g ]
  live:
    permission: sakuraguilds.live
    permission-message: '&cNie posiadasz uprawnień.'
  help:
    aliases: [ pomoc ]
