name: SakuraGuilds
version: ${version}
main: me.xneox.guilds.SakuraGuildsPlugin
author: awumii
description: Work-in-progress guild plugin.
api-version: 1.19

depend:
  - Vault

softdepend:
  - WorldEdit
  - FastAsyncWorldEdit
  - PlaceholderAPI
  - HolographicDisplays

commands:
  guild:
    aliases: [ g ]